"""Content bank for the multi-slide educational carousels (matching the
reference template style the account owner supplied). Each topic is a
short 3-slide carousel: a cover/hook, a content slide with 3 panels, and a
closing slide with a CTA toward the Telegram channel / DMs.

main.py (once carousel posting is wired in) picks one topic per scheduled
carousel post, renders each slide with carousel_composer.build_slide, and
publishes them as a single Instagram carousel (album) post.
"""

BRAND_CORNER_LEFT = ["PLAN", "ANALYZE", "TRADE", "GROW"]
BRAND_CORNER_RIGHT = ["GOLD", "DISCIPLINE", "PATIENCE", "FREEDOM"]

CTA_TELEGRAM = "Follow -- Telegram channel in bio"
CTA_TELEGRAM_ALT = "Telegram in bio for full access"
CTA_FOLLOW = "Follow for daily XAUUSD insights"
CTA_BOT = "Message us to get the bot"
CTA_BOT_ALT = "DM us for license & support"

# Persian equivalents -- used for CAROUSELS_FA below, rendered on
# Persian-language days (see ENGLISH_WEEKDAYS in main.py).
BRAND_CORNER_LEFT_FA = ["برنامه", "تحلیل", "معامله", "رشد"]
BRAND_CORNER_RIGHT_FA = ["طلا", "نظم", "صبر", "آزادی"]

CTA_TELEGRAM_FA = "فالو کن -- کانال تلگرام تو بایو"
CTA_TELEGRAM_ALT_FA = "برای دسترسی کامل، تلگرام تو بایو"
CTA_FOLLOW_FA = "فالو کن برای تحلیل روزانه XAUUSD"
CTA_BOT_FA = "برای دریافت ربات پیام بده"
CTA_BOT_ALT_FA = "برای لایسنس و پشتیبانی دایرکت بده"


def _panel(icon, title, desc):
    return (icon, title, desc)


CAROUSELS = [
    {
        "id": "know-when-to-stay-out",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["candlestick chart screen", "gold bars", "trading desk"],
        "slides": [
            {
                "headline_lines": [("KNOW WHEN", "white"), ("TO STAY OUT", "gold")],
                "body_text": "A low-quality setup can cost more than a missed opportunity. Some days the right trade is no trade at all.",
                "panels": [],
                "takeaway_text": "Swipe for the 3 warning signs.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("DISCIPLINE TODAY", "A STRONGER TOMORROW"),
                "top_right_words": ["SAME", "MARKETS", "HIGHER", "STANDARDS"],
            },
            {
                "headline_lines": [("THREE SIGNS", "white"), ("TO STAY FLAT", "gold")],
                "body_text": "If direction is unclear, volatility is random, or price is trapped in noise, staying flat is a professional decision.",
                "panels": [
                    _panel("arrows_swap", "No Clear Bias", "Higher-timeframe direction is mixed"),
                    _panel("bar_chart", "Messy Structure", "Levels are crowded or weak"),
                    _panel("document", "News Noise", "Price becomes too reactive to trust"),
                ],
                "takeaway_text": "No trade is better than a forced trade.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("DISCIPLINE TODAY", "A STRONGER TOMORROW"),
                "top_right_words": ["SAME", "MARKETS", "HIGHER", "STANDARDS"],
            },
            {
                "headline_lines": [("PATIENCE IS", "white"), ("A POSITION TOO", "gold")],
                "body_text": "Waiting for a clean setup protects your capital the same way a good stop-loss does.",
                "panels": [],
                "takeaway_text": "Clarity protects capital.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("DISCIPLINE TODAY", "A STRONGER TOMORROW"),
                "top_right_words": ["SAME", "MARKETS", "HIGHER", "STANDARDS"],
            },
        ],
    },
    {
        "id": "after-a-loss",
        "category": "XAUUSD | TRADING PSYCHOLOGY",
        "search_terms": ["hourglass", "gold bars", "focused trader desk"],
        "slides": [
            {
                "headline_lines": [("AFTER A LOSS,", "white"), ("DON'T RUSH BACK IN", "gold")],
                "body_text": "Emotional re-entry usually creates a second mistake. The market will still be there in ten minutes.",
                "panels": [],
                "takeaway_text": "Swipe for the 3-step reset.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["CLEARER", "TRADERS", "STRONGER", "TOMORROW"],
            },
            {
                "headline_lines": [("PAUSE.", "white"), ("REVIEW. RE-ENTER.", "gold")],
                "body_text": "Pause for a moment, review what actually happened, and only return once your plan is clear again.",
                "panels": [
                    _panel("clock", "Pause", "Step away for a moment"),
                    _panel("search", "Review", "Look at the setup, not the feeling"),
                    _panel("target", "Re-enter", "Only with a clear mind"),
                ],
                "takeaway_text": "Emotional control is part of the strategy.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["CLEARER", "TRADERS", "STRONGER", "TOMORROW"],
            },
            {
                "headline_lines": [("ONE LOSS", "white"), ("ISN'T A CRISIS", "gold")],
                "body_text": "It's data. Log it, learn from it, and let your plan -- not your ego -- decide the next trade.",
                "panels": [],
                "takeaway_text": "A calmer mind, a sharper trader.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["CLEARER", "TRADERS", "STRONGER", "TOMORROW"],
            },
        ],
    },
    {
        "id": "trading-journal",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["leather journal pen", "gold bars", "candlestick chart screen"],
        "slides": [
            {
                "headline_lines": [("A TRADING JOURNAL", "white"), ("BUILDS CONSISTENCY", "gold")],
                "body_text": "If you don't record your trades, the same mistakes repeat. A journal shows what works and what doesn't.",
                "panels": [],
                "takeaway_text": "Swipe for what to log.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["DISCIPLINE", "TURNS", "TRADES", "INTO", "FREEDOM"],
            },
            {
                "headline_lines": [("LOG.", "white"), ("TRACK. LEARN.", "gold")],
                "body_text": "Every entry deserves three lines: why you took it, what happened, and what you'd do differently.",
                "panels": [
                    _panel("document", "Entry Reason", "Clarity creates better trades"),
                    _panel("bar_chart", "Result", "See what works and what doesn't"),
                    _panel("gear", "Pattern", "Turn experience into progress"),
                ],
                "takeaway_text": "Professional traders don't just trade -- they review.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["DISCIPLINE", "TURNS", "TRADES", "INTO", "FREEDOM"],
            },
            {
                "headline_lines": [("YOUR JOURNAL", "white"), ("IS YOUR EDGE", "gold")],
                "body_text": "Over time it tells you more about your trading than any indicator ever will.",
                "panels": [],
                "takeaway_text": "Better trades, a brighter tomorrow.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["DISCIPLINE", "TURNS", "TRADES", "INTO", "FREEDOM"],
            },
        ],
    },
    {
        "id": "real-breakout-or-fakeout",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["candlestick chart screen", "gold bars", "financial graph"],
        "slides": [
            {
                "headline_lines": [("REAL BREAKOUT", "white"), ("OR FAKEOUT?", "gold")],
                "body_text": "Not every move through a level is a true breakout. Wait for confirmation before you follow price.",
                "panels": [],
                "takeaway_text": "Swipe for the 3-step check.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("BETTER", "ANALYSIS"),
                "top_right_words": ["A", "BRIGHTER", "TOMORROW"],
            },
            {
                "headline_lines": [("CONFIRMATION", "white"), ("BEATS SPEED", "gold")],
                "body_text": "A real breakout closes beyond the level, retests it, and keeps going in the same direction.",
                "panels": [
                    _panel("bar_chart", "Candle Close", "Beyond the level, not just a wick"),
                    _panel("arrows_swap", "Retest Holds", "As new support or resistance"),
                    _panel("trend_up", "Momentum", "Continues in the same direction"),
                ],
                "takeaway_text": "Confirmation matters more than speed.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("BETTER", "ANALYSIS"),
                "top_right_words": ["A", "BRIGHTER", "TOMORROW"],
            },
            {
                "headline_lines": [("CHASING A", "white"), ("FAKEOUT COSTS MORE", "gold")],
                "body_text": "One extra candle of patience is cheaper than one bad entry.",
                "panels": [],
                "takeaway_text": "Follow for smarter XAUUSD setups.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("BETTER", "ANALYSIS"),
                "top_right_words": ["A", "BRIGHTER", "TOMORROW"],
            },
        ],
    },
    {
        "id": "protect-your-capital",
        "category": "XAUUSD | RISK MANAGEMENT",
        "search_terms": ["gold bars", "financial graph", "calculator desk"],
        "slides": [
            {
                "headline_lines": [("PROTECT", "white"), ("YOUR CAPITAL", "gold")],
                "body_text": "Successful traders manage risk, not just trades.",
                "panels": [],
                "takeaway_text": "Swipe for the 3 rules.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("TRADE SMARTER", "A BRIGHTER TOMORROW"),
                "top_right_words": ["RISK", "FIRST", "PROFIT", "SECOND"],
            },
            {
                "headline_lines": [("STOP-LOSS.", "white"), ("SIZE. RATIO.", "gold")],
                "body_text": "Define your risk before you enter, keep position size reasonable, and aim for at least 1:2 reward.",
                "panels": [
                    _panel("shield", "Use Stop-Loss", "Always define your risk before entry"),
                    _panel("scale", "Risk 1-2%", "Keep your position size reasonable"),
                    _panel("target", "Reward Ratio", "Aim for at least 1:2 on every setup"),
                ],
                "takeaway_text": "Small risks protect bigger opportunities.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("TRADE SMARTER", "A BRIGHTER TOMORROW"),
                "top_right_words": ["RISK", "FIRST", "PROFIT", "SECOND"],
            },
            {
                "headline_lines": [("A GOOD PLAN", "white"), ("KEEPS YOU IN THE GAME", "gold")],
                "body_text": "It won't guarantee profits, but it will keep you around long enough to get good.",
                "panels": [],
                "takeaway_text": "Follow for disciplined XAUUSD content.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("TRADE SMARTER", "A BRIGHTER TOMORROW"),
                "top_right_words": ["RISK", "FIRST", "PROFIT", "SECOND"],
            },
        ],
    },
    {
        "id": "patience-pays",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["chess pieces", "gold bars", "candlestick chart screen"],
        "slides": [
            {
                "headline_lines": [("PATIENCE PAYS", "white"), ("MORE THAN IMPULSE", "gold")],
                "body_text": "The best opportunities appear when structure, timing, and confirmation align.",
                "panels": [],
                "takeaway_text": "Swipe for what to check first.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("SAME MARKETS", "A HIGHER MINDSET"),
                "top_right_words": ["STRATEGY", "OVER", "EMOTION"],
            },
            {
                "headline_lines": [("STRUCTURE.", "white"), ("TIMING. CONFIRMATION.", "gold")],
                "body_text": "A skipped trade can protect your capital as much as a good entry can grow it.",
                "panels": [
                    _panel("bar_chart", "Structure", "Read the chart, not the noise"),
                    _panel("clock", "Timing", "Right session, right moment"),
                    _panel("search", "Confirmation", "Let price prove the idea first"),
                ],
                "takeaway_text": "Wait for quality, not noise.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("SAME MARKETS", "A HIGHER MINDSET"),
                "top_right_words": ["STRATEGY", "OVER", "EMOTION"],
            },
            {
                "headline_lines": [("THE TRADE YOU", "white"), ("SKIP COUNTS TOO", "gold")],
                "body_text": "Discipline creates opportunity -- most of it happens before you click buy or sell.",
                "panels": [],
                "takeaway_text": "Follow for a calmer approach to XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("SAME MARKETS", "A HIGHER MINDSET"),
                "top_right_words": ["STRATEGY", "OVER", "EMOTION"],
            },
        ],
    },
    {
        "id": "retest-beats-chase",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["candlestick chart screen", "gold bars", "trading desk"],
        "slides": [
            {
                "headline_lines": [("A RETEST", "white"), ("BEATS A CHASE", "gold")],
                "body_text": "Not every breakout deserves an instant entry. Stronger setups often come after price proves the level.",
                "panels": [],
                "takeaway_text": "Swipe to see the difference.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("DISCIPLINE", "CREATES OPPORTUNITY"),
                "top_right_words": ["A", "BETTER", "TRADER", "TOMORROW"],
            },
            {
                "headline_lines": [("CHASING VS.", "white"), ("WAITING FOR THE RETEST", "gold")],
                "body_text": "Chasing means a late entry with weak control. A retest means a clear level and better timing.",
                "panels": [
                    _panel("arrows_swap", "Chasing", "Late entry, weak control"),
                    _panel("target", "Retest", "Clear level, better timing"),
                    _panel("shield", "Confirmation", "Reduces emotional entries"),
                ],
                "takeaway_text": "Let the market prove it first.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("DISCIPLINE", "CREATES OPPORTUNITY"),
                "top_right_words": ["A", "BETTER", "TRADER", "TOMORROW"],
            },
            {
                "headline_lines": [("ONE MISSED", "white"), ("ENTRY WON'T HURT YOU", "gold")],
                "body_text": "One bad chase, repeated for a year, will. Play the odds, not the FOMO.",
                "panels": [],
                "takeaway_text": "Better trades, brighter days.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("DISCIPLINE", "CREATES OPPORTUNITY"),
                "top_right_words": ["A", "BETTER", "TRADER", "TOMORROW"],
            },
        ],
    },
    {
        "id": "small-risk-lasts-longer",
        "category": "XAUUSD | RISK MANAGEMENT",
        "search_terms": ["gold bars", "financial graph", "calculator desk"],
        "slides": [
            {
                "headline_lines": [("SMALL RISK", "white"), ("LASTS LONGER", "gold")],
                "body_text": "Good trading isn't built on one big win. It's built on controlled risk, trade after trade.",
                "panels": [],
                "takeaway_text": "Swipe for the 3 pillars.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("SAME MARKETS", "A HIGHER MINDSET"),
                "top_right_words": ["DISCIPLINE", "CREATES", "OPPORTUNITY"],
            },
            {
                "headline_lines": [("STOP-LOSS.", "white"), ("SIZE. PROTECTION.", "gold")],
                "body_text": "A clear stop-loss and a position size that matches your plan are what let you trade tomorrow too.",
                "panels": [
                    _panel("shield", "Stop-Loss", "Protects your capital first"),
                    _panel("scale", "Position Size", "Matched to your plan, not your mood"),
                    _panel("coins", "Capital Protection", "The real long game"),
                ],
                "takeaway_text": "Protection keeps you in the game.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("SAME MARKETS", "A HIGHER MINDSET"),
                "top_right_words": ["DISCIPLINE", "CREATES", "OPPORTUNITY"],
            },
            {
                "headline_lines": [("PRESERVE FIRST.", "white"), ("GROW SECOND.", "gold")],
                "body_text": "Every trader who lasted long enough to get good did it by staying in the game.",
                "panels": [],
                "takeaway_text": "Follow for practical XAUUSD risk management.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("SAME MARKETS", "A HIGHER MINDSET"),
                "top_right_words": ["DISCIPLINE", "CREATES", "OPPORTUNITY"],
            },
        ],
    },
    {
        "id": "one-market-two-tempos",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["city skyline night", "candlestick chart screen", "gold bars"],
        "slides": [
            {
                "headline_lines": [("ONE MARKET.", "white"), ("TWO TEMPOS.", "gold")],
                "body_text": "Gold doesn't behave the same way all day. London and New York trade very differently.",
                "panels": [],
                "takeaway_text": "Swipe for the session breakdown.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("DIFFERENT SESSIONS", "GREATER OPPORTUNITIES"),
                "top_right_words": ["GLOBAL", "MARKETS", "REAL", "OPPORTUNITIES"],
            },
            {
                "headline_lines": [("LONDON VS.", "white"), ("NEW YORK", "gold")],
                "body_text": "London often brings cleaner structure. New York can bring stronger reactions and sharp reversals.",
                "panels": [
                    _panel("bar_chart", "London", "Cleaner momentum, structured moves"),
                    _panel("trend_up", "New York", "Higher reaction speed, bigger volatility"),
                    _panel("clock", "Prepare", "Know which session you're trading"),
                ],
                "takeaway_text": "Read the session before you read the entry.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("DIFFERENT SESSIONS", "GREATER OPPORTUNITIES"),
                "top_right_words": ["GLOBAL", "MARKETS", "REAL", "OPPORTUNITIES"],
            },
            {
                "headline_lines": [("SAME CHART.", "white"), ("DIFFERENT RULES.", "gold")],
                "body_text": "A plan built for one session rarely works well in the other -- adjust, don't force it.",
                "panels": [],
                "takeaway_text": "Follow for smarter session-based content.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("DIFFERENT SESSIONS", "GREATER OPPORTUNITIES"),
                "top_right_words": ["GLOBAL", "MARKETS", "REAL", "OPPORTUNITIES"],
            },
        ],
    },
    {
        "id": "when-news-hits",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["financial graph", "gold bars", "candlestick chart screen"],
        "slides": [
            {
                "headline_lines": [("WHEN NEWS HITS,", "white"), ("DISCIPLINE MATTERS MORE", "gold")],
                "body_text": "Economic releases can accelerate gold and expand volatility fast.",
                "panels": [],
                "takeaway_text": "Swipe for how to prepare.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("INFORMATION MOVES", "MARKETS FASTER"),
                "top_right_words": ["SAME", "PRINCIPLES", "BIGGER", "OPPORTUNITIES"],
            },
            {
                "headline_lines": [("VOLATILITY.", "white"), ("PREPARATION. PROTECTION.", "gold")],
                "body_text": "Spreads widen and candles expand -- mark key levels before the release, then protect your size.",
                "panels": [
                    _panel("bar_chart", "Volatility", "Spreads widen, candles expand"),
                    _panel("document", "Preparation", "Mark key levels before the release"),
                    _panel("shield", "Protection", "Reduce size or wait for confirmation"),
                ],
                "takeaway_text": "Strong traders stay structured in fast markets.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("INFORMATION MOVES", "MARKETS FASTER"),
                "top_right_words": ["SAME", "PRINCIPLES", "BIGGER", "OPPORTUNITIES"],
            },
            {
                "headline_lines": [("SPEED CHANGES.", "white"), ("RULES DON'T.", "gold")],
                "body_text": "Your process still depends on levels, risk limits, and confirmation -- news or not.",
                "panels": [],
                "takeaway_text": "Follow for practical gold trading ideas.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("INFORMATION MOVES", "MARKETS FASTER"),
                "top_right_words": ["SAME", "PRINCIPLES", "BIGGER", "OPPORTUNITIES"],
            },
        ],
    },
    {
        "id": "smart-trading-starts-before-entry",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["gold bullion bars stacked", "candlestick chart screen", "trading desk"],
        "slides": [
            {
                "headline_lines": [("SMART TRADING", "white"), ("STARTS BEFORE THE ENTRY", "gold")],
                "body_text": "Before you enter any gold trade, check the bigger trend, key levels, and market structure.",
                "panels": [],
                "takeaway_text": "Swipe for the 3-point checklist.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["BETTER", "ANALYSIS", "A BRIGHTER", "TOMORROW"],
            },
            {
                "headline_lines": [("TREND.", "white"), ("LEVELS. STRUCTURE.", "gold")],
                "body_text": "Good entries are prepared, not guessed -- these three things come before every trade idea.",
                "panels": [
                    _panel("trend_up", "Trend", "Follow the bigger picture"),
                    _panel("bar_chart", "Key Levels", "Find opportunities at key zones"),
                    _panel("target", "Structure", "Understand the market flow"),
                ],
                "takeaway_text": "Better analysis, a brighter tomorrow.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["BETTER", "ANALYSIS", "A BRIGHTER", "TOMORROW"],
            },
            {
                "headline_lines": [("PREPARATION IS", "white"), ("PART OF THE TRADE", "gold")],
                "body_text": "The chart rewards the trader who did the work before the candle closed.",
                "panels": [],
                "takeaway_text": "Follow for daily XAUUSD insights.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["BETTER", "ANALYSIS", "A BRIGHTER", "TOMORROW"],
            },
        ],
    },
    {
        "id": "layered-entries-need-a-plan",
        "category": "XAUUSD | GOLD TRADING",
        "search_terms": ["gold bars", "candlestick chart screen", "financial graph"],
        "slides": [
            {
                "headline_lines": [("LAYERED ENTRIES", "white"), ("NEED A CLEAR PLAN", "gold")],
                "body_text": "Adding into a trade only makes sense when the scenario is defined from the start.",
                "panels": [],
                "takeaway_text": "Swipe for the 3 conditions.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["SAME", "MARKET", "HIGHER", "STANDARDS"],
            },
            {
                "headline_lines": [("SCENARIO.", "white"), ("STOP. SIZE.", "gold")],
                "body_text": "Know exactly when to add, protect your capital first, and keep total risk balanced.",
                "panels": [
                    _panel("document", "Defined Scenario", "Know exactly when to add"),
                    _panel("shield", "Clear Stop-Loss", "Protect your capital first"),
                    _panel("coins", "Controlled Size", "Keep risk balanced"),
                ],
                "takeaway_text": "Without a plan, layered entries only increase risk.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["SAME", "MARKET", "HIGHER", "STANDARDS"],
            },
            {
                "headline_lines": [("ADDING SIZE", "white"), ("IS A DECISION", "gold")],
                "body_text": "Not a reaction. Treat every add like a new trade with its own rules.",
                "panels": [],
                "takeaway_text": "Follow for better XAUUSD execution.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["SAME", "MARKET", "HIGHER", "STANDARDS"],
            },
        ],
    },
    {
        "id": "how-the-bot-works",
        "category": "XAUUSD | AUTO TRADING BOT",
        "slides": [
            {
                "headline_lines": [("TRADING", "white"), ("WITHOUT THE MANUAL WORK", "gold")],
                "body_text": "Every trade shared in our Telegram signal channel is executed by our own bot -- exactly as posted, with no manual clicks.",
                "panels": [],
                "takeaway_text": "Swipe to see how it works.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("SIGNAL IN", "TRADE OUT"),
                "top_right_words": ["ZERO", "MANUAL", "EXECUTION"],
            },
            {
                "headline_lines": [("SIGNAL.", "white"), ("EXECUTION. DONE.", "gold")],
                "body_text": "From our Telegram channel to your MetaTrader 5 -- the whole process runs on its own.",
                "panels": [
                    _panel("search", "Signal", "Every trade shared in our Telegram channel"),
                    _panel("gear", "Execution", "The bot places it on MT5 automatically"),
                    _panel("arrows_swap", "Entry & Exit", "Fully automatic, no manual clicks"),
                ],
                "takeaway_text": "Set it up once. Let it run.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("SIGNAL IN", "TRADE OUT"),
                "top_right_words": ["ZERO", "MANUAL", "EXECUTION"],
            },
            {
                "headline_lines": [("RUNS ON MT5.", "white"), ("NOT YOUR PHONE.", "gold")],
                "body_text": "Installed on MetaTrader 5, on your own computer -- built for precision, not convenience.",
                "panels": [],
                "takeaway_text": "Consistency beats emotion.",
                "cta_text": CTA_BOT,
                "top_left_tagline": ("SIGNAL IN", "TRADE OUT"),
                "top_right_words": ["ZERO", "MANUAL", "EXECUTION"],
            },
        ],
    },
    {
        "id": "bot-compatibility-and-license",
        "category": "XAUUSD | AUTO TRADING BOT",
        "slides": [
            {
                "headline_lines": [("ONE BOT.", "white"), ("ANY BROKER. ANY PROP FIRM.", "gold")],
                "body_text": "Our bot connects to any broker and any major prop firm -- you set the lot size, it handles the rest with precision.",
                "panels": [
                    _panel("scale", "Broker", "Works with any broker you trade with"),
                    _panel("shield", "Prop Firm", "Compatible with major prop firms"),
                    _panel("target", "Lot Size", "You control the size, we handle the rest"),
                ],
                "takeaway_text": "Same bot. Any account.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("BUILT FOR", "XAUUSD"),
                "top_right_words": ["BROKER", "AND PROP", "READY"],
            },
            {
                "headline_lines": [("A PRESET", "white"), ("BUILT FOR GOLD", "gold")],
                "body_text": "A ready-made, pre-optimized preset for XAUUSD -- and fully configurable for other pairs and indices too.",
                "panels": [
                    _panel("coins", "XAUUSD", "Pre-optimized, ready to run"),
                    _panel("bar_chart", "Other Markets", "EURUSD, NAS100, US30 and more"),
                    _panel("gear", "Fully Configurable", "Adjust settings anytime"),
                ],
                "takeaway_text": "Ready in minutes, not hours.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("BUILT FOR", "XAUUSD"),
                "top_right_words": ["BROKER", "AND PROP", "READY"],
            },
            {
                "headline_lines": [("6 OR 12 MONTHS.", "white"), ("FULL SUPPORT.", "gold")],
                "body_text": "Choose a 6-month or 1-year license -- full support included for as long as your license runs.",
                "panels": [],
                "takeaway_text": "Simple licensing. Real support.",
                "cta_text": CTA_BOT_ALT,
                "top_left_tagline": ("BUILT FOR", "XAUUSD"),
                "top_right_words": ["BROKER", "AND PROP", "READY"],
            },
        ],
    },
    {
        "id": "success-is-what-you-dont-see",
        "category": "XAUUSD | TRADING MINDSET",
        "slides": [
            {
                "headline_lines": [("SUCCESS IN TRADING", "white"), ("ISN'T WHAT YOU SEE", "gold")],
                "body_text": "Everyone sees the profit. Almost no one sees what it actually took to get there.",
                "panels": [],
                "takeaway_text": "Swipe for what's underneath.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["GOLD", "DISCIPLINE", "FREEDOM"],
            },
            {
                "headline_lines": [("THE PART", "white"), ("NOBODY POSTS", "gold")],
                "body_text": "The profit is the tip. This is what's actually underneath it.",
                "panels": [
                    _panel("target", "Discipline", "Follow the plan, not the mood"),
                    _panel("shield", "Risk Management", "Protect capital before profit"),
                    _panel("clock", "Patience", "Wait for the setup, not the clock"),
                ],
                "takeaway_text": "None of this shows up in a screenshot.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["GOLD", "DISCIPLINE", "FREEDOM"],
            },
            {
                "headline_lines": [("PROFIT IS JUST", "white"), ("THE TIP OF IT", "gold")],
                "body_text": "Everything underneath -- discipline, risk, patience -- is the real edge.",
                "panels": [],
                "takeaway_text": "Build the part nobody sees.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("PLAN", "ANALYZE"),
                "top_right_words": ["GOLD", "DISCIPLINE", "FREEDOM"],
            },
        ],
    },
    {
        "id": "one-timeframe-isnt-enough",
        "category": "XAUUSD | TECHNICAL ANALYSIS",
        "slides": [
            {
                "headline_lines": [("STOP TRADING XAUUSD", "white"), ("ON ONE TIMEFRAME", "gold")],
                "body_text": "The bigger picture changes everything about how you read an entry.",
                "panels": [],
                "takeaway_text": "Swipe for the 3-step read.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("SAME MARKETS", "HIGHER STANDARDS"),
                "top_right_words": ["CONTEXT", "THEN", "ENTRY"],
            },
            {
                "headline_lines": [("CONTEXT FIRST.", "white"), ("ENTRY LAST.", "gold")],
                "body_text": "Zoom out before you zoom in -- in this order, every time.",
                "panels": [
                    _panel("globe", "Market Context", "Start on the higher timeframe"),
                    _panel("bar_chart", "Structure & Liquidity", "Find where price actually reacts"),
                    _panel("target", "Entry", "Zoom in only once context lines up"),
                ],
                "takeaway_text": "Skipping a step is how good setups fail.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("SAME MARKETS", "HIGHER STANDARDS"),
                "top_right_words": ["CONTEXT", "THEN", "ENTRY"],
            },
            {
                "headline_lines": [("SEE THE BIGGER PICTURE.", "white"), ("TAKE BETTER TRADES.", "gold")],
                "body_text": "Multi-timeframe reading isn't complicated. It's just patient.",
                "panels": [],
                "takeaway_text": "Zoom out before you zoom in.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("SAME MARKETS", "HIGHER STANDARDS"),
                "top_right_words": ["CONTEXT", "THEN", "ENTRY"],
            },
        ],
    },
    {
        "id": "gold-trading-tips-that-hold-up",
        "category": "XAUUSD | GOLD TRADING",
        "slides": [
            {
                "headline_lines": [("GOLD TRADING TIPS", "white"), ("THAT ACTUALLY HOLD UP", "gold")],
                "body_text": "Simple rules that protect your capital and improve your results.",
                "panels": [],
                "takeaway_text": "Swipe for the rules.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("DISCIPLINE TODAY", "A STRONGER TOMORROW"),
                "top_right_words": ["PLAN", "EXECUTE", "REVIEW"],
            },
            {
                "headline_lines": [("THREE RULES", "white"), ("BEFORE ANY TRADE", "gold")],
                "body_text": "Skip one of these and the other two stop mattering.",
                "panels": [
                    _panel("trend_up", "Follow The Trend", "Trade with the higher-timeframe direction"),
                    _panel("bar_chart", "Respect Key Levels", "Gold reacts hard at real S/R zones"),
                    _panel("shield", "Risk First", "Protecting capital beats being right"),
                ],
                "takeaway_text": "Simple rules, applied consistently, beat clever ones applied rarely.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("DISCIPLINE TODAY", "A STRONGER TOMORROW"),
                "top_right_words": ["PLAN", "EXECUTE", "REVIEW"],
            },
            {
                "headline_lines": [("PLAN. EXECUTE.", "white"), ("REVIEW. REPEAT.", "gold")],
                "body_text": "Consistency is the edge -- focus on process, not any single trade.",
                "panels": [],
                "takeaway_text": "Process over any single outcome.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("DISCIPLINE TODAY", "A STRONGER TOMORROW"),
                "top_right_words": ["PLAN", "EXECUTE", "REVIEW"],
            },
        ],
    },
    {
        "id": "best-time-to-trade-gold",
        "category": "XAUUSD | MARKET SESSIONS",
        "slides": [
            {
                "headline_lines": [("TIMING MATTERS", "white"), ("MORE THAN YOU THINK", "gold")],
                "body_text": "Gold moves differently depending on which session is active.",
                "panels": [],
                "takeaway_text": "Swipe for the best window.",
                "cta_text": CTA_FOLLOW,
                "top_left_tagline": ("SAME MARKET", "HIGHER STANDARDS"),
                "top_right_words": ["SESSIONS", "AND", "LIQUIDITY"],
            },
            {
                "headline_lines": [("LIQUIDITY", "white"), ("FOLLOWS THE CLOCK", "gold")],
                "body_text": "Volume and volatility both shift hard depending on which session is live.",
                "panels": [
                    _panel("clock", "London-NY Overlap", "Highest volatility, biggest moves"),
                    _panel("globe", "Asian Session", "Usually quieter, tighter ranges"),
                    _panel("bar_chart", "News Windows", "CPI, NFP and FOMC change everything"),
                ],
                "takeaway_text": "Same chart, different market depending on the hour.",
                "cta_text": CTA_TELEGRAM,
                "top_left_tagline": ("SAME MARKET", "HIGHER STANDARDS"),
                "top_right_words": ["SESSIONS", "AND", "LIQUIDITY"],
            },
            {
                "headline_lines": [("RIGHT TIME.", "white"), ("RIGHT SETUP.", "gold")],
                "body_text": "The London-New York overlap is where liquidity -- and opportunity -- peaks.",
                "panels": [],
                "takeaway_text": "Trade the hours that reward you.",
                "cta_text": CTA_TELEGRAM_ALT,
                "top_left_tagline": ("SAME MARKET", "HIGHER STANDARDS"),
                "top_right_words": ["SESSIONS", "AND", "LIQUIDITY"],
            },
        ],
    },
]

# Persian translation of CAROUSELS, same ids/structure/icons, rendered with
# carousel_composer.build_slide(..., rtl=True) on Persian-language days (see
# ENGLISH_WEEKDAYS in main.py).
CAROUSELS_FA = [
    {
        "id": "know-when-to-stay-out",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("یاد بگیر کِی", "white"), ("وارد نشی", "gold")],
                "body_text": "یک ستاپ ضعیف می‌تونه گرون‌تر از یک فرصت ازدست‌رفته تموم بشه. بعضی روزها بهترین معامله، هیچ معامله‌ای نیست.",
                "panels": [],
                "takeaway_text": "برای ۳ نشونه‌ی هشدار، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("نظم امروز", "فردای قوی‌تر"),
                "top_right_words": ["همون", "بازار", "استاندارد", "بالاتر"],
            },
            {
                "headline_lines": [("سه نشونه", "white"), ("برای کنار موندن", "gold")],
                "body_text": "اگه جهت بازار نامشخصه، نوسان تصادفیه، یا قیمت تو نویز گیر کرده، بی‌معامله موندن یک تصمیم حرفه‌ایه.",
                "panels": [
                    _panel("arrows_swap", "جهت نامشخص", "روند تایم‌فریم بالاتر مشخص نیست"),
                    _panel("bar_chart", "ساختار درهم", "سطوح شلوغ یا ضعیفن"),
                    _panel("document", "نویز خبری", "قیمت بیش‌ازحد به خبر واکنش نشون می‌ده"),
                ],
                "takeaway_text": "بی‌معامله موندن بهتر از معامله‌ی اجباریه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("نظم امروز", "فردای قوی‌تر"),
                "top_right_words": ["همون", "بازار", "استاندارد", "بالاتر"],
            },
            {
                "headline_lines": [("صبر هم", "white"), ("یک پوزیشنه", "gold")],
                "body_text": "صبر کردن برای یک ستاپ تمیز، دقیقاً مثل یک حد ضرر خوب از سرمایه‌ت محافظت می‌کنه.",
                "panels": [],
                "takeaway_text": "وضوح، سرمایه رو حفظ می‌کنه.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("نظم امروز", "فردای قوی‌تر"),
                "top_right_words": ["همون", "بازار", "استاندارد", "بالاتر"],
            },
        ],
    },
    {
        "id": "after-a-loss",
        "category": "XAUUSD | روانشناسی معامله‌گری",
        "slides": [
            {
                "headline_lines": [("بعد از یک ضرر،", "white"), ("عجله نکن برگردی", "gold")],
                "body_text": "ورود احساسی معمولاً یک اشتباه دوم می‌سازه. بازار ده دقیقه‌ی دیگه هم همون‌جاست.",
                "panels": [],
                "takeaway_text": "برای ریست ۳مرحله‌ای، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["ذهن", "شفاف‌تر", "فردای", "قوی‌تر"],
            },
            {
                "headline_lines": [("مکث کن.", "white"), ("مرور کن. برگرد.", "gold")],
                "body_text": "یک لحظه مکث کن، ببین واقعاً چه اتفاقی افتاد، و فقط وقتی برگرد که برنامه‌ت دوباره روشن باشه.",
                "panels": [
                    _panel("clock", "مکث", "یه لحظه فاصله بگیر"),
                    _panel("search", "مرور", "به ستاپ نگاه کن، نه به احساست"),
                    _panel("target", "بازگشت", "فقط با ذهن روشن"),
                ],
                "takeaway_text": "کنترل احساسات، بخشی از استراتژیه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["ذهن", "شفاف‌تر", "فردای", "قوی‌تر"],
            },
            {
                "headline_lines": [("یک ضرر", "white"), ("یک بحران نیست", "gold")],
                "body_text": "این فقط یک داده‌ست. ثبتش کن، ازش یاد بگیر، و بذار برنامه‌ت -- نه غرورت -- معامله‌ی بعدی رو تصمیم بگیره.",
                "panels": [],
                "takeaway_text": "ذهن آروم‌تر، معامله‌گر دقیق‌تر.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["ذهن", "شفاف‌تر", "فردای", "قوی‌تر"],
            },
        ],
    },
    {
        "id": "trading-journal",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("ژورنال معاملاتی", "white"), ("ثبات می‌سازه", "gold")],
                "body_text": "اگه معاملاتت رو ثبت نکنی، همون اشتباه‌ها تکرار می‌شن. ژورنال نشون می‌ده چی جواب می‌ده و چی نه.",
                "panels": [],
                "takeaway_text": "برای چی‌هایی که باید ثبت کنی، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["نظم", "معامله", "رو", "آزادی", "می‌کنه"],
            },
            {
                "headline_lines": [("ثبت کن.", "white"), ("پیگیری. یادگیری.", "gold")],
                "body_text": "هر ورود سه خط می‌خواد: چرا واردش شدی، چی شد، و دفعه‌ی بعد چی رو فرق می‌ذاری.",
                "panels": [
                    _panel("document", "دلیل ورود", "وضوح، معامله‌ی بهتر می‌سازه"),
                    _panel("bar_chart", "نتیجه", "ببین چی جواب می‌ده و چی نه"),
                    _panel("gear", "الگو", "تجربه رو به پیشرفت تبدیل کن"),
                ],
                "takeaway_text": "معامله‌گر حرفه‌ای فقط معامله نمی‌کنه -- مرور هم می‌کنه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["نظم", "معامله", "رو", "آزادی", "می‌کنه"],
            },
            {
                "headline_lines": [("ژورنالت", "white"), ("مزیت توئه", "gold")],
                "body_text": "با گذر زمان، بیشتر از هر اندیکاتوری درباره‌ی معاملاتت بهت می‌گه.",
                "panels": [],
                "takeaway_text": "معامله‌ی بهتر، فردای روشن‌تر.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["نظم", "معامله", "رو", "آزادی", "می‌کنه"],
            },
        ],
    },
    {
        "id": "real-breakout-or-fakeout",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("شکست واقعیه", "white"), ("یا فیک؟", "gold")],
                "body_text": "هر عبور از یک سطح، شکست واقعی نیست. قبل از دنبال کردن قیمت، منتظر تأیید بمون.",
                "panels": [],
                "takeaway_text": "برای چک ۳مرحله‌ای، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("تحلیل", "بهتر"),
                "top_right_words": ["فردای", "روشن‌تر"],
            },
            {
                "headline_lines": [("تأیید", "white"), ("از سرعت مهم‌تره", "gold")],
                "body_text": "شکست واقعی، بالای سطح بسته می‌شه، دوباره تستش می‌کنه، و همون جهت رو ادامه می‌ده.",
                "panels": [
                    _panel("bar_chart", "بسته شدن کندل", "بالای سطح، نه فقط سایه"),
                    _panel("arrows_swap", "نگه‌داشتن ریتست", "به‌عنوان حمایت یا مقاومت جدید"),
                    _panel("trend_up", "مومنتوم", "در همون جهت ادامه پیدا می‌کنه"),
                ],
                "takeaway_text": "تأیید مهم‌تر از سرعته.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("تحلیل", "بهتر"),
                "top_right_words": ["فردای", "روشن‌تر"],
            },
            {
                "headline_lines": [("دنبال کردن", "white"), ("فیک، گرون‌تره", "gold")],
                "body_text": "یک کندل بیشتر صبر کردن، ارزون‌تر از یک ورود بده.",
                "panels": [],
                "takeaway_text": "فالو کن برای ستاپ‌های هوشمندانه‌ی XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("تحلیل", "بهتر"),
                "top_right_words": ["فردای", "روشن‌تر"],
            },
        ],
    },
    {
        "id": "protect-your-capital",
        "category": "XAUUSD | مدیریت ریسک",
        "slides": [
            {
                "headline_lines": [("از سرمایه‌ت", "white"), ("محافظت کن", "gold")],
                "body_text": "معامله‌گر موفق فقط معامله نمی‌کنه، ریسک رو مدیریت می‌کنه.",
                "panels": [],
                "takeaway_text": "برای ۳ قانون، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("معامله‌ی هوشمندانه‌تر", "فردای روشن‌تر"),
                "top_right_words": ["اول", "ریسک", "بعد", "سود"],
            },
            {
                "headline_lines": [("حد ضرر.", "white"), ("حجم. نسبت.", "gold")],
                "body_text": "قبل از ورود ریسکت رو مشخص کن، حجم پوزیشن رو منطقی نگه دار، و حداقل نسبت ۱:۲ رو هدف بگیر.",
                "panels": [
                    _panel("shield", "از حد ضرر استفاده کن", "همیشه قبل از ورود ریسکت رو مشخص کن"),
                    _panel("scale", "ریسک ۱ تا ۲٪", "حجم پوزیشنت رو منطقی نگه دار"),
                    _panel("target", "نسبت ریوارد", "تو هر ستاپ حداقل ۱:۲ رو هدف بگیر"),
                ],
                "takeaway_text": "ریسک‌های کوچیک، فرصت‌های بزرگ‌تر رو حفظ می‌کنن.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("معامله‌ی هوشمندانه‌تر", "فردای روشن‌تر"),
                "top_right_words": ["اول", "ریسک", "بعد", "سود"],
            },
            {
                "headline_lines": [("یک برنامه‌ی خوب", "white"), ("تو رو تو بازی نگه می‌داره", "gold")],
                "body_text": "سود رو تضمین نمی‌کنه، ولی اونقدر نگهت می‌داره تا حرفه‌ای بشی.",
                "panels": [],
                "takeaway_text": "فالو کن برای محتوای منظم XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("معامله‌ی هوشمندانه‌تر", "فردای روشن‌تر"),
                "top_right_words": ["اول", "ریسک", "بعد", "سود"],
            },
        ],
    },
    {
        "id": "patience-pays",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("صبر", "white"), ("بیشتر از عجله جواب می‌ده", "gold")],
                "body_text": "بهترین فرصت‌ها وقتی پیدا می‌شن که ساختار، زمان‌بندی، و تأیید هم‌راستا بشن.",
                "panels": [],
                "takeaway_text": "برای اولین چیزی که باید چک کنی، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("همون بازارها", "ذهنیت بالاتر"),
                "top_right_words": ["استراتژی", "به‌جای", "احساسات"],
            },
            {
                "headline_lines": [("ساختار.", "white"), ("زمان‌بندی. تأیید.", "gold")],
                "body_text": "یک معامله‌ی رد شده می‌تونه به اندازه‌ی یک ورود خوب، سرمایه‌ت رو حفظ کنه.",
                "panels": [
                    _panel("bar_chart", "ساختار", "چارت رو بخون، نه نویز رو"),
                    _panel("clock", "زمان‌بندی", "سشن درست، لحظه‌ی درست"),
                    _panel("search", "تأیید", "بذار قیمت اول ایده رو ثابت کنه"),
                ],
                "takeaway_text": "منتظر کیفیت باش، نه نویز.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("همون بازارها", "ذهنیت بالاتر"),
                "top_right_words": ["استراتژی", "به‌جای", "احساسات"],
            },
            {
                "headline_lines": [("معامله‌ای که", "white"), ("رد می‌کنی هم مهمه", "gold")],
                "body_text": "نظم، فرصت می‌سازه -- بیشترش قبل از زدن دکمه‌ی خرید یا فروش اتفاق می‌افته.",
                "panels": [],
                "takeaway_text": "فالو کن برای رویکردی آروم‌تر به XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("همون بازارها", "ذهنیت بالاتر"),
                "top_right_words": ["استراتژی", "به‌جای", "احساسات"],
            },
        ],
    },
    {
        "id": "retest-beats-chase",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("ریتست", "white"), ("بهتر از دنبال کردنه", "gold")],
                "body_text": "هر شکستی ورود فوری نمی‌خواد. ستاپ‌های قوی‌تر معمولاً بعد از اینکه قیمت سطح رو ثابت کرد، میان.",
                "panels": [],
                "takeaway_text": "برای دیدن فرق، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("نظم", "فرصت می‌سازه"),
                "top_right_words": ["معامله‌گر", "بهتر", "فردا"],
            },
            {
                "headline_lines": [("دنبال کردن", "white"), ("در برابر صبر برای ریتست", "gold")],
                "body_text": "دنبال کردن یعنی ورود دیر با کنترل ضعیف. ریتست یعنی سطح واضح و زمان‌بندی بهتر.",
                "panels": [
                    _panel("arrows_swap", "دنبال کردن", "ورود دیر، کنترل ضعیف"),
                    _panel("target", "ریتست", "سطح واضح، زمان‌بندی بهتر"),
                    _panel("shield", "تأیید", "ورودهای احساسی رو کم می‌کنه"),
                ],
                "takeaway_text": "بذار بازار اول ثابتش کنه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("نظم", "فرصت می‌سازه"),
                "top_right_words": ["معامله‌گر", "بهتر", "فردا"],
            },
            {
                "headline_lines": [("یک ورود", "white"), ("ازدست‌رفته آسیبی نمی‌زنه", "gold")],
                "body_text": "ولی یک دنبال‌کردن بد، اگه یک سال تکرار بشه، می‌زنه. با احتمالات بازی کن، نه با FOMO.",
                "panels": [],
                "takeaway_text": "معامله‌ی بهتر، روزهای روشن‌تر.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("نظم", "فرصت می‌سازه"),
                "top_right_words": ["معامله‌گر", "بهتر", "فردا"],
            },
        ],
    },
    {
        "id": "small-risk-lasts-longer",
        "category": "XAUUSD | مدیریت ریسک",
        "slides": [
            {
                "headline_lines": [("ریسک کوچیک", "white"), ("عمر بیشتری داره", "gold")],
                "body_text": "معامله‌گری خوب با یک برد بزرگ ساخته نمی‌شه. با ریسک کنترل‌شده، معامله به معامله ساخته می‌شه.",
                "panels": [],
                "takeaway_text": "برای ۳ ستون اصلی، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("همون بازارها", "ذهنیت بالاتر"),
                "top_right_words": ["نظم", "فرصت", "می‌سازه"],
            },
            {
                "headline_lines": [("حد ضرر.", "white"), ("حجم. محافظت.", "gold")],
                "body_text": "یک حد ضرر واضح و حجمی متناسب با برنامه‌ت، همونیه که می‌ذاره فردا هم معامله کنی.",
                "panels": [
                    _panel("shield", "حد ضرر", "اول از سرمایه‌ت محافظت می‌کنه"),
                    _panel("scale", "حجم پوزیشن", "متناسب با برنامه‌ت، نه حالت روحیت"),
                    _panel("coins", "محافظت از سرمایه", "بازی واقعیِ بلندمدت"),
                ],
                "takeaway_text": "محافظت، تو رو تو بازی نگه می‌داره.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("همون بازارها", "ذهنیت بالاتر"),
                "top_right_words": ["نظم", "فرصت", "می‌سازه"],
            },
            {
                "headline_lines": [("اول حفظ کن.", "white"), ("بعد رشد بده.", "gold")],
                "body_text": "هر معامله‌گری که اونقدر دووم آورد تا حرفه‌ای بشه، با موندن تو بازی این کار رو کرد.",
                "panels": [],
                "takeaway_text": "فالو کن برای مدیریت ریسک عملیِ XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("همون بازارها", "ذهنیت بالاتر"),
                "top_right_words": ["نظم", "فرصت", "می‌سازه"],
            },
        ],
    },
    {
        "id": "one-market-two-tempos",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("یک بازار.", "white"), ("دو ریتم.", "gold")],
                "body_text": "طلا تمام روز یک‌جور رفتار نمی‌کنه. لندن و نیویورک خیلی متفاوت معامله می‌شن.",
                "panels": [],
                "takeaway_text": "برای جزئیات سشن‌ها، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("سشن‌های متفاوت", "فرصت‌های بزرگ‌تر"),
                "top_right_words": ["بازارهای", "جهانی", "فرصت‌های", "واقعی"],
            },
            {
                "headline_lines": [("لندن", "white"), ("در برابر نیویورک", "gold")],
                "body_text": "لندن معمولاً ساختار تمیزتری میاره. نیویورک می‌تونه واکنش‌های قوی‌تر و برگشت‌های تیز بیاره.",
                "panels": [
                    _panel("bar_chart", "لندن", "مومنتوم تمیزتر، حرکات ساختاریافته"),
                    _panel("trend_up", "نیویورک", "سرعت واکنش بالاتر، نوسان بزرگ‌تر"),
                    _panel("clock", "آماده‌سازی", "بدون تو کدوم سشن معامله می‌کنی"),
                ],
                "takeaway_text": "قبل از خوندن ورود، سشن رو بخون.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("سشن‌های متفاوت", "فرصت‌های بزرگ‌تر"),
                "top_right_words": ["بازارهای", "جهانی", "فرصت‌های", "واقعی"],
            },
            {
                "headline_lines": [("چارت یکیه.", "white"), ("قوانین فرق داره.", "gold")],
                "body_text": "برنامه‌ای که برای یک سشن ساخته شده، به‌ندرت تو سشن دیگه خوب کار می‌کنه -- تنظیمش کن، به زور پیش نبر.",
                "panels": [],
                "takeaway_text": "فالو کن برای محتوای هوشمندانه بر پایه‌ی سشن.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("سشن‌های متفاوت", "فرصت‌های بزرگ‌تر"),
                "top_right_words": ["بازارهای", "جهانی", "فرصت‌های", "واقعی"],
            },
        ],
    },
    {
        "id": "when-news-hits",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("وقتی خبر میاد،", "white"), ("نظم مهم‌تر می‌شه", "gold")],
                "body_text": "انتشار داده‌های اقتصادی می‌تونه طلا رو سریع تکون بده و نوسان رو زیاد کنه.",
                "panels": [],
                "takeaway_text": "برای نحوه‌ی آماده شدن، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("اطلاعات", "بازار رو سریع‌تر می‌چرخونه"),
                "top_right_words": ["همون اصول", "فرصت‌های", "بزرگ‌تر"],
            },
            {
                "headline_lines": [("نوسان.", "white"), ("آمادگی. محافظت.", "gold")],
                "body_text": "اسپردها بازتر و کندل‌ها بزرگ‌تر می‌شن -- قبل از انتشار خبر سطوح کلیدی رو مشخص کن، بعد حجمت رو محافظت کن.",
                "panels": [
                    _panel("bar_chart", "نوسان", "اسپرد بازتر، کندل بزرگ‌تر می‌شه"),
                    _panel("document", "آمادگی", "قبل از خبر سطوح کلیدی رو مشخص کن"),
                    _panel("shield", "محافظت", "حجم رو کم کن یا منتظر تأیید بمون"),
                ],
                "takeaway_text": "معامله‌گر قوی تو بازار سریع هم منظم می‌مونه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("اطلاعات", "بازار رو سریع‌تر می‌چرخونه"),
                "top_right_words": ["همون اصول", "فرصت‌های", "بزرگ‌تر"],
            },
            {
                "headline_lines": [("سرعت عوض می‌شه.", "white"), ("قوانین نه.", "gold")],
                "body_text": "فرآیندت هنوز به سطوح، محدودیت ریسک، و تأیید بستگی داره -- خبر باشه یا نباشه.",
                "panels": [],
                "takeaway_text": "فالو کن برای ایده‌های عملی معامله‌ی طلا.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("اطلاعات", "بازار رو سریع‌تر می‌چرخونه"),
                "top_right_words": ["همون اصول", "فرصت‌های", "بزرگ‌تر"],
            },
        ],
    },
    {
        "id": "smart-trading-starts-before-entry",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("معامله‌ی هوشمندانه", "white"), ("قبل از ورود شروع می‌شه", "gold")],
                "body_text": "قبل از هر معامله‌ی طلا، روند بزرگ‌تر، سطوح کلیدی، و ساختار بازار رو چک کن.",
                "panels": [],
                "takeaway_text": "برای چک‌لیست ۳موردی، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["تحلیل", "بهتر", "فردای", "روشن‌تر"],
            },
            {
                "headline_lines": [("روند.", "white"), ("سطوح. ساختار.", "gold")],
                "body_text": "ورود خوب، آماده‌شده‌ست نه حدسی -- این سه مورد قبل از هر ایده‌ی معامله میان.",
                "panels": [
                    _panel("trend_up", "روند", "تصویر بزرگ‌تر رو دنبال کن"),
                    _panel("bar_chart", "سطوح کلیدی", "فرصت‌ها رو تو نواحی کلیدی پیدا کن"),
                    _panel("target", "ساختار", "جریان بازار رو بفهم"),
                ],
                "takeaway_text": "تحلیل بهتر، فردای روشن‌تر.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["تحلیل", "بهتر", "فردای", "روشن‌تر"],
            },
            {
                "headline_lines": [("آمادگی", "white"), ("بخشی از معامله‌ست", "gold")],
                "body_text": "چارت به معامله‌گری پاداش می‌ده که قبل از بسته شدن کندل کارش رو انجام داده.",
                "panels": [],
                "takeaway_text": "فالو کن برای تحلیل روزانه XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["تحلیل", "بهتر", "فردای", "روشن‌تر"],
            },
        ],
    },
    {
        "id": "layered-entries-need-a-plan",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("ورود پله‌ای", "white"), ("به برنامه‌ی واضح نیاز داره", "gold")],
                "body_text": "اضافه کردن به معامله فقط وقتی معنی داره که سناریو از اول مشخص باشه.",
                "panels": [],
                "takeaway_text": "برای ۳ شرط، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["همون بازار", "استاندارد", "بالاتر"],
            },
            {
                "headline_lines": [("سناریو.", "white"), ("حد ضرر. حجم.", "gold")],
                "body_text": "دقیقاً بدون کِی اضافه کنی، اول از سرمایه‌ت محافظت کن، و ریسک کل رو متعادل نگه دار.",
                "panels": [
                    _panel("document", "سناریوی مشخص", "دقیقاً بدون کِی اضافه کنی"),
                    _panel("shield", "حد ضرر واضح", "اول از سرمایه‌ت محافظت کن"),
                    _panel("coins", "حجم کنترل‌شده", "ریسک رو متعادل نگه دار"),
                ],
                "takeaway_text": "بدون برنامه، ورود پله‌ای فقط ریسک رو زیاد می‌کنه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["همون بازار", "استاندارد", "بالاتر"],
            },
            {
                "headline_lines": [("اضافه کردن حجم", "white"), ("یک تصمیمه", "gold")],
                "body_text": "نه یک واکنش. با هر اضافه‌کردن مثل یک معامله‌ی جدید با قوانین خودش رفتار کن.",
                "panels": [],
                "takeaway_text": "فالو کن برای اجرای بهتر XAUUSD.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["همون بازار", "استاندارد", "بالاتر"],
            },
        ],
    },
    {
        "id": "how-the-bot-works",
        "category": "XAUUSD | ربات معامله‌گر خودکار",
        "slides": [
            {
                "headline_lines": [("معامله", "white"), ("بدون کار دستی", "gold")],
                "body_text": "هر سیگنالی که تو کانال تلگرام‌مون می‌ذاریم، توسط ربات خودمون اجرا می‌شه -- دقیقاً همون‌طور که پست شده، بدون کلیک دستی.",
                "panels": [],
                "takeaway_text": "برای دیدن نحوه‌ی کارش، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("سیگنال ورودی", "معامله‌ی خروجی"),
                "top_right_words": ["اجرای", "صد در صد", "خودکار"],
            },
            {
                "headline_lines": [("سیگنال.", "white"), ("اجرا. تموم.", "gold")],
                "body_text": "از کانال تلگرام‌مون تا MetaTrader 5 خودت -- کل فرآیند خودکار پیش می‌ره.",
                "panels": [
                    _panel("search", "سیگنال", "هر معامله‌ای که تو کانال تلگرام‌مون به اشتراک گذاشته می‌شه"),
                    _panel("gear", "اجرا", "ربات به‌طور خودکار روی MT5 اجراش می‌کنه"),
                    _panel("arrows_swap", "ورود و خروج", "کاملاً خودکار، بدون کلیک دستی"),
                ],
                "takeaway_text": "یک بار تنظیمش کن. بذار کار کنه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("سیگنال ورودی", "معامله‌ی خروجی"),
                "top_right_words": ["اجرای", "صد در صد", "خودکار"],
            },
            {
                "headline_lines": [("روی MT5 اجرا می‌شه.", "white"), ("نه گوشیت.", "gold")],
                "body_text": "روی MetaTrader 5، روی کامپیوتر خودت نصب می‌شه -- برای دقت ساخته شده، نه راحتی.",
                "panels": [],
                "takeaway_text": "ثبات از احساسات مهم‌تره.",
                "cta_text": CTA_BOT_FA,
                "top_left_tagline": ("سیگنال ورودی", "معامله‌ی خروجی"),
                "top_right_words": ["اجرای", "صد در صد", "خودکار"],
            },
        ],
    },
    {
        "id": "bot-compatibility-and-license",
        "category": "XAUUSD | ربات معامله‌گر خودکار",
        "slides": [
            {
                "headline_lines": [("یک ربات.", "white"), ("هر بروکر. هر پراپ‌فرم.", "gold")],
                "body_text": "ربات ما به هر بروکر و هر پراپ‌فرم بزرگی وصل می‌شه -- تو حجم معامله رو مشخص کن، بقیه‌ش رو با دقت انجام می‌ده.",
                "panels": [
                    _panel("scale", "بروکر", "با هر بروکری که باهاش معامله می‌کنی کار می‌کنه"),
                    _panel("shield", "پراپ‌فرم", "با پراپ‌فرم‌های بزرگ سازگاره"),
                    _panel("target", "حجم معامله", "حجم دست توئه، بقیه‌ش با ماست"),
                ],
                "takeaway_text": "همون ربات. هر حسابی.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("ساخته‌شده برای", "XAUUSD"),
                "top_right_words": ["آماده‌ی", "بروکر", "و پراپ"],
            },
            {
                "headline_lines": [("یک پریست", "white"), ("ساخته‌شده برای طلا", "gold")],
                "body_text": "یک پریست آماده و بهینه‌شده برای XAUUSD -- و کاملاً قابل تنظیم برای جفت‌ارزها و شاخص‌های دیگه هم.",
                "panels": [
                    _panel("coins", "XAUUSD", "بهینه‌شده، آماده‌ی اجرا"),
                    _panel("bar_chart", "بازارهای دیگه", "EURUSD، NAS100، US30 و بیشتر"),
                    _panel("gear", "کاملاً قابل تنظیم", "هر وقت خواستی تنظیماتش رو عوض کن"),
                ],
                "takeaway_text": "آماده در چند دقیقه، نه ساعت‌ها.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("ساخته‌شده برای", "XAUUSD"),
                "top_right_words": ["آماده‌ی", "بروکر", "و پراپ"],
            },
            {
                "headline_lines": [("۶ یا ۱۲ ماه.", "white"), ("پشتیبانی کامل.", "gold")],
                "body_text": "لایسنس ۶ ماهه یا ۱ ساله رو انتخاب کن -- تا وقتی لایسنست فعاله، پشتیبانی کامل شامل می‌شه.",
                "panels": [],
                "takeaway_text": "لایسنس ساده. پشتیبانی واقعی.",
                "cta_text": CTA_BOT_ALT_FA,
                "top_left_tagline": ("ساخته‌شده برای", "XAUUSD"),
                "top_right_words": ["آماده‌ی", "بروکر", "و پراپ"],
            },
        ],
    },
    {
        "id": "success-is-what-you-dont-see",
        "category": "XAUUSD | ذهنیت معامله‌گری",
        "slides": [
            {
                "headline_lines": [("موفقیت تو معامله‌گری", "white"), ("چیزی نیست که می‌بینی", "gold")],
                "body_text": "همه سود رو می‌بینن. تقریباً هیچ‌کس نمی‌بینه چی لازم بوده تا بهش برسه.",
                "panels": [],
                "takeaway_text": "برای دیدن چیزی که زیرشه، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["طلا", "نظم", "آزادی"],
            },
            {
                "headline_lines": [("قسمتی که", "white"), ("هیچ‌کس پست نمی‌کنه", "gold")],
                "body_text": "سود فقط نوکشه. این چیزیه که واقعاً زیرشه.",
                "panels": [
                    _panel("target", "نظم", "برنامه رو دنبال کن، نه حالت رو"),
                    _panel("shield", "مدیریت ریسک", "قبل از سود، از سرمایه محافظت کن"),
                    _panel("clock", "صبر", "منتظر ستاپ باش، نه ساعت"),
                ],
                "takeaway_text": "هیچ‌کدوم از این‌ها تو یک اسکرین‌شات دیده نمی‌شه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["طلا", "نظم", "آزادی"],
            },
            {
                "headline_lines": [("سود فقط", "white"), ("نوک ماجراست", "gold")],
                "body_text": "همه‌چیزی که زیرشه -- نظم، ریسک، صبر -- مزیت واقعیه.",
                "panels": [],
                "takeaway_text": "قسمتی رو بساز که کسی نمی‌بینه.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("برنامه", "تحلیل"),
                "top_right_words": ["طلا", "نظم", "آزادی"],
            },
        ],
    },
    {
        "id": "one-timeframe-isnt-enough",
        "category": "XAUUSD | تحلیل تکنیکال",
        "slides": [
            {
                "headline_lines": [("دیگه XAUUSD رو", "white"), ("تو یک تایم‌فریم معامله نکن", "gold")],
                "body_text": "تصویر بزرگ‌تر همه‌چیز رو درباره‌ی نحوه‌ی خوندن یک ورود عوض می‌کنه.",
                "panels": [],
                "takeaway_text": "برای خوندن ۳مرحله‌ای، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("همون بازارها", "استاندارد بالاتر"),
                "top_right_words": ["اول زمینه", "بعد", "ورود"],
            },
            {
                "headline_lines": [("اول زمینه.", "white"), ("در آخر ورود.", "gold")],
                "body_text": "قبل از زوم کردن، اول دور بشو -- هر بار به همین ترتیب.",
                "panels": [
                    _panel("globe", "زمینه‌ی بازار", "از تایم‌فریم بالاتر شروع کن"),
                    _panel("bar_chart", "ساختار و نقدینگی", "جایی رو پیدا کن که قیمت واقعاً واکنش نشون می‌ده"),
                    _panel("target", "ورود", "فقط وقتی زمینه هماهنگ شد، زوم کن"),
                ],
                "takeaway_text": "رد کردن یک مرحله، دلیل شکست ستاپ‌های خوبه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("همون بازارها", "استاندارد بالاتر"),
                "top_right_words": ["اول زمینه", "بعد", "ورود"],
            },
            {
                "headline_lines": [("تصویر بزرگ‌تر رو ببین.", "white"), ("معامله‌ی بهتر بگیر.", "gold")],
                "body_text": "خوندن چند تایم‌فریم پیچیده نیست. فقط صبورانه‌ست.",
                "panels": [],
                "takeaway_text": "قبل از زوم، دور شو.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("همون بازارها", "استاندارد بالاتر"),
                "top_right_words": ["اول زمینه", "بعد", "ورود"],
            },
        ],
    },
    {
        "id": "gold-trading-tips-that-hold-up",
        "category": "XAUUSD | معامله طلا",
        "slides": [
            {
                "headline_lines": [("نکاتی برای معامله‌ی طلا", "white"), ("که واقعاً جواب می‌دن", "gold")],
                "body_text": "قوانین ساده‌ای که از سرمایه‌ت محافظت می‌کنن و نتیجه‌ت رو بهتر می‌کنن.",
                "panels": [],
                "takeaway_text": "برای دیدن قوانین، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("نظم امروز", "فردای قوی‌تر"),
                "top_right_words": ["برنامه", "اجرا", "مرور"],
            },
            {
                "headline_lines": [("سه قانون", "white"), ("قبل از هر معامله", "gold")],
                "body_text": "یکی از این‌ها رو رد کن، اون دو تای دیگه هم دیگه مهم نیستن.",
                "panels": [
                    _panel("trend_up", "روند رو دنبال کن", "با جهت تایم‌فریم بالاتر معامله کن"),
                    _panel("bar_chart", "به سطوح کلیدی احترام بذار", "طلا تو نواحی حمایت/مقاومت واقعی شدید واکنش می‌ده"),
                    _panel("shield", "اول ریسک", "حفظ سرمایه از درست بودن مهم‌تره"),
                ],
                "takeaway_text": "قوانین ساده‌ای که همیشه رعایت بشن، از قوانین باهوشی که به‌ندرت رعایت می‌شن بهترن.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("نظم امروز", "فردای قوی‌تر"),
                "top_right_words": ["برنامه", "اجرا", "مرور"],
            },
            {
                "headline_lines": [("برنامه. اجرا.", "white"), ("مرور. تکرار.", "gold")],
                "body_text": "ثبات، مزیت اصلیه -- روی فرآیند تمرکز کن، نه یک معامله‌ی خاص.",
                "panels": [],
                "takeaway_text": "فرآیند مهم‌تره، نه یک نتیجه‌ی خاص.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("نظم امروز", "فردای قوی‌تر"),
                "top_right_words": ["برنامه", "اجرا", "مرور"],
            },
        ],
    },
    {
        "id": "best-time-to-trade-gold",
        "category": "XAUUSD | سشن‌های بازار",
        "slides": [
            {
                "headline_lines": [("زمان‌بندی", "white"), ("بیشتر از چیزی که فکر می‌کنی مهمه", "gold")],
                "body_text": "طلا بسته به اینکه کدوم سشن فعاله، متفاوت حرکت می‌کنه.",
                "panels": [],
                "takeaway_text": "برای بهترین بازه‌ی زمانی، بکش.",
                "cta_text": CTA_FOLLOW_FA,
                "top_left_tagline": ("همون بازار", "استاندارد بالاتر"),
                "top_right_words": ["سشن‌ها", "و", "نقدینگی"],
            },
            {
                "headline_lines": [("نقدینگی", "white"), ("از ساعت پیروی می‌کنه", "gold")],
                "body_text": "حجم و نوسان هر دو بسته به سشن فعال، شدیداً تغییر می‌کنن.",
                "panels": [
                    _panel("clock", "همپوشانی لندن-نیویورک", "بیشترین نوسان، بزرگ‌ترین حرکات"),
                    _panel("globe", "سشن آسیا", "معمولاً آرام‌تر، رنج‌های محدودتر"),
                    _panel("bar_chart", "بازه‌های خبری", "CPI، NFP و FOMC همه‌چیز رو عوض می‌کنن"),
                ],
                "takeaway_text": "چارت یکیه، ولی بسته به ساعت، بازار فرق می‌کنه.",
                "cta_text": CTA_TELEGRAM_FA,
                "top_left_tagline": ("همون بازار", "استاندارد بالاتر"),
                "top_right_words": ["سشن‌ها", "و", "نقدینگی"],
            },
            {
                "headline_lines": [("زمان درست.", "white"), ("ستاپ درست.", "gold")],
                "body_text": "همپوشانی لندن-نیویورک جاییه که نقدینگی -- و فرصت -- به اوج می‌رسه.",
                "panels": [],
                "takeaway_text": "تو ساعت‌هایی معامله کن که بهت پاداش می‌دن.",
                "cta_text": CTA_TELEGRAM_ALT_FA,
                "top_left_tagline": ("همون بازار", "استاندارد بالاتر"),
                "top_right_words": ["سشن‌ها", "و", "نقدینگی"],
            },
        ],
    },
]
